Update sphp

diff --git a/sphp b/sphp
--- a/sphp
+++ b/sphp
@@ -9,13 +9,13 @@ fi
 
 # Usage
 if [ $# -ne 1 ]; then
-	echo "Usage: sphp [phpversion]"
-	echo "Versions installed:"
-	brew list | grep '^php[0-9]\{2,\}$' | grep -o -E '[0-9]+' | while read -r line ; do
-    	echo " - phpversion: $line"
-	    # your code goes here
-	done
-	exit 1
+  echo "Usage: sphp [phpversion]"
+  echo "Versions installed:"
+  brew list | grep '^php[0-9]\{2,\}$' | grep -o -E '[0-9]+' | while read -r line ; do
+      echo " - phpversion: $line"
+      # your code goes here
+  done
+  exit 1
 fi
 
 currentversion="`php -r \"error_reporting(0); echo str_replace('.', '', substr(phpversion(), 0, 3));\"`"
@@ -28,54 +28,52 @@ minorNew=${newversion:1:1}
 brew list php$newversion 2> /dev/null > /dev/null
 
 if [ $? -eq 0 ]; then
-	echo "PHP version $newversion found"
+  echo "PHP version $newversion found"
 
-	# Check if new version is already the current version.
-	if [ "${newversion}" == "${currentversion}" ]; then
-	    echo -n "PHP version ${newversion} is already being used. Continue by reloading? (y/n) "
-	    while true; do
-	        read -n 1 yn
-	        case $yn in
-	            [Yy]* ) echo && break;;
-	            [Nn]* ) echo && exit 1;;
-	        esac
-	    done
-	fi
+  # Check if new version is already the current version.
+  if [ "${newversion}" == "${currentversion}" ]; then
+      echo -n "PHP version ${newversion} is already being used. Continue by reloading? (y/n) "
+      while true; do
+          read -n 1 yn
+          case $yn in
+              [Yy]* ) echo && break;;
+              [Nn]* ) echo && exit 1;;
+          esac
+      done
+  fi
 
-	echo "Unlinking old binaries..."
-	brew unlink php$currentversion 2> /dev/null > /dev/null
-	brew unlink php${currentversion}-apcu 2> /dev/null > /dev/null
+  echo "Unlinking old binaries..."
+  brew unlink php$currentversion 2> /dev/null > /dev/null
 
-	echo "Linking new binaries..."
-	brew link php$newversion
-	brew link php${newversion}-apcu
+  echo "Linking new binaries..."
+  brew link php$newversion
 
-	echo "Linking new modphp addon..."
-	sudo ln -sf `brew list php$newversion | grep libphp` /usr/local/lib/libphp${majorNew}.so
+  echo "Linking new modphp addon..."
+  sudo ln -sf `brew list php$newversion | grep libphp` /usr/local/lib/libphp${majorNew}.so
 
-	echo "Fixing LoadModule..."
-	apacheConf=`httpd -V | grep -i server_config_file | cut -d '"' -f 2`
-	sudo sed -i -e "/LoadModule php${majorOld}_module/s/^#*/#/" $apacheConf
+  echo "Fixing LoadModule..."
+  apacheConf=`httpd -V | grep -i server_config_file | cut -d '"' -f 2`
+  sudo sed -i -e "/LoadModule php${majorOld}_module/s/^#*/#/" $apacheConf
 
-	if grep "LoadModule php${majorNew}_module .*php${newversion}" $apacheConf > /dev/null
-	then 
-		sudo sed -i -e "/LoadModule php${majorNew}_module .*php${newversion}/s/^#//" $apacheConf
-	else
-		sudo sed -i -e "/LoadModule php${majorNew}_module/s/^#//" $apacheConf
-	fi
+  if grep "LoadModule php${majorNew}_module .*php${newversion}" $apacheConf > /dev/null
+  then
+    sudo sed -i -e "/LoadModule php${majorNew}_module .*php${newversion}/s/^#//" $apacheConf
+  else
+    sudo sed -i -e "/LoadModule php${majorNew}_module/s/^#//" $apacheConf
+  fi
 
 
-	echo "Updating version file..."
+  echo "Updating version file..."
 
-	echo "Restarting homebrew Apache..."
-	sudo apachectl -k restart > /dev/null 2>&1
-	
-	echo "Done."
+  echo "Restarting Apache..."
+  sudo apachectl -k restart
 
-	# Show PHP CLI version for verification.
-	echo && php -v
+  echo "Done."
+
+  # Show PHP CLI version for verification.
+  echo && php -v
 else
-	echo "PHP version $majorNew.$minorNew was not found."
-	echo "Try \`brew install php${newversion}\` first."
-	exit 1
+  echo "PHP version $majorNew.$minorNew was not found."
+  echo "Try \`brew install php${newversion}\` first."
+  exit 1
 fi
